version: "3.8"
services:
    aerospikedb:
        image: aerospike/aerospike-server:latest
        container_name: aerospike
        ports:
        - 3000-3002:3000-3002
        volumes:
        - ./data:/opt/aerospike/data/
    demorevcontent:

      image: demorevcontent:1.0
      container_name: demorevcontent
      restart: always
      ports:
        - 8080:8080
      depends_on:
        - aerospikedb
volumes:
  data: {}

networks:
  default:
    name: revcontent_network