version: "3.8"
services:

  demorevcontent:
    build:
      context: .
      # network: revcontent_network
      args: 
        - aero_host=${HOST}
        - aero_port=${PORT}
        - aero_namespace=${NAMESPACE}
        - aero_set=${SET}      
      dockerfile: Dockerfile
    image: demorevcontent:${IMG_VERSION}
    environment:
      - aero_host=${HOST}
      - aero_port=${PORT}
      - aero_namespace=${NAMESPACE}
      - aero_set=${SET}      
    ports:
      - 8080:8080
    depends_on:
      - aerospikedb
    volumes:
      - ./:/app
    restart: always
  aerospikedb:
      image: aerospike/aerospike-server:latest
      container_name: aerospike
      ports:
      - 3000-3002:3000-3002
      volumes:
      - ./data:/opt/aerospike/data/
volumes:
  data: {}

networks:
  default:
    name: revcontent_network